$schema: "https://json-schema.org/draft/2020-12/schema"
description: Configuration schema for the DSA-phasing pipeline
properties:
  manifest:
    type: string
    description: Path to a table with the manifest of samples to be processed.

required:
  - manifest
